### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FRANkiller13** [sandyh90/rockstream-streaming-relay-laravel#11]
`Sat Jun 24 05:37:13 2023] PHP Warning:  require(/root/web/rockstream-streaming-relay-1.0.4/rockstream_stream_repeater/web/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /root/web/rockstream-streaming-relay-1.0.4/rockstream_stream_repeater/web/public/index.php on line 34
[Sat Jun 24 05:37:13 2023] PHP Fatal error:  Uncaught Error: Failed opening required '/root/web/rockstream-streaming-relay-1.0.4/rockstream_stream_repeater/web/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /root/web/rockstream-streaming-relay-1.0.4/rockstream_stream_repeater/web/public/index.php:34
Stack trace:
#0 /root/web/rockstream-streaming-relay-1.0.4/rockstream_stream_repeater/web/server.php(21): require_once()
#1 {main}
  thrown in /root/web/rockstream-streaming-relay-1.0.4/rockstream_stream_repeater/web/public/index.php on line 34
[Sat Jun 24 05:37:13 2023] [::1]:47412 Closing`

i have done everything u saying on Installation tutorial.. i test the app on windows and it worked.. on linux some .phps are missing... any help please ?

**Comment by sandyh90** [comment]
Hi @FRANkiller13 
Hmm, are you already running the command ``composer install`` to install dependency I think that error is cause there's no dependency installed because this app requires another dependency.

**Comment by FRANkiller13** [comment]
First of all thank you very much for your reply @sandyh90 

I will try again the whole installation on fresh OS, im using debian is there any difference ?

**Comment by sandyh90** [comment]
@FRANkiller13 i think there's no any difference because as i said before you should run command ``composer install`` if you don't run that command to install the required dependency for the application, you just get the same error as before.
