### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by kd48888** [sandyh90/rockstream-streaming-relay-laravel#12]
Hello,

Would it be possible to add an API that can be accessed externally? Or at least only for the output target?

**Comment by sandyh90** [comment]
Hi, sorry for the delay in answering, yes you can access this application externally with api but you have to create a new route that can be accessed via api and compatible with the existing controller.

**Comment by kd48888** [comment]
Could you push the version with the API ? or tell me how to do it ?
