### ISSUE TITLE
Linux Config

### ISSUE THREAD

**Issue by N-harzallah** [sandyh90/rockstream-streaming-relay-laravel#2]
helle thank you for your awesome work, i installed the script on UBUNTU 20.04. i can login

but how to override all settings that load .exe file to work with installed nginx & ffmpeg on ubuntu ?

**Comment by sandyh90** [comment]
Hi @N-harzallah, if you want to override the run program setting on Linux you need to change some code and shell to run a command that is related to the windows version

1. First, on the file **"web_http/app/Component/Utility.php"** take a look at the function in the following section 
- **"public static function getInstanceRun()"**,  
- **"public static function getInstanceRunByPath()"**, 
- **"public static function runInstancewithPid()"** 
you need to change the shell command run and change the code if there have a different output between windows and Linux

2. Second, on the folder **"web_http/app/Console/Command"** there's have 3 main files that related to the Nginx command run
<table border="1">
        <tr>
            <th>Files</th>
            <th>Need Change</th>
        </tr>
        <tr>
            <td>NginxConfigCommand.php</td>
            <td rowspan="3">
                <table border="1">
                    <tr>
                        <th>Functions</th>
                        <th>Description</th>
                        <th>Line Code</th>
                    </tr>
                    <tr>
                        <td>Utility::runInstancewithPid()</td>
                        <td>Change shell run command</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>!file_exists($nginx_folder . '\nginx.exe')</td>
                        <td>Change file checker for nginx executable</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Utility::getInstanceRunByPath()</td>
                        <td>Change process checker</td>
                        <td></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>NginxPowerCommand.php</td>
        </tr>
        <tr>
            <td>NginxReloadCommand.php</td>
        </tr>
    </table>

3. Thirdly, on the folder **"web_http/app/http/controllers"** there have 2 files that you need to change
<table border="1">
        <tr>
            <th>Files</th>
            <th>Need Change</th>
        </tr>
        <tr>
            <td>PremiereVideoController.php</td>
            <td rowspan="2">
                <table border="1">
                    <tr>
                        <th>Functions</th>
                        <th>Description</th>
                        <th>Line Code</th>
                    </tr>
                    <tr>
                        <td>Utility::runInstancewithPid()</td>
                        <td>Change shell run command</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>!file_exists($php_folder . DIRECTORY_SEPARATOR . 'php.rockstream.exe')</td>
                        <td>Change file checker for php executable</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Utility::getInstanceRunByPath()</td>
                        <td>Change process checker</td>
                        <td></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>InterfaceSettingsController.php</td>
        </tr>
    </table>

4. Fourth, on the folder **"web_http/app/jobs"** there have 2 files that you need to change
<table border="1">
        <tr>
            <th>Files</th>
            <th>Need Change</th>
        </tr>
        <tr>
            <td>PremiereVideoBroadcast.php</td>
            <td>
                <table border="1">
                    <tr>
                        <th>Function</th>
                        <th>Description</th>
                        <th>Line Code</th>
                    </tr>
                    <tr>
                        <td>"ffprobe.binaries" and "ffmpeg.binaries"</td>
                        <td>Change executable format ffmpeg and ffprobe</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>!file_exists($ffmpeg_folder . DIRECTORY_SEPARATOR . 'ffmpeg.exe') || !file_exists($ffmpeg_folder . DIRECTORY_SEPARATOR . 'ffprobe.exe')</td>
                        <td>Change file checker for ffmpeg and ffprobe</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Utility::getInstanceRunByPath()</td>
                        <td>Change process checker</td>
                        <td></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>TestStreamingBroadcast.php</td>
            <td>
                <table border="1">
                    <tr>
                        <th>Functions</th>
                        <th>Description</th>
                        <th>Line Code</th>
                    </tr>
                    <tr>
                        <td>system('start "Test Stream FFMpeg" /d"{$ffmpeg_folder}" "ffmpeg.exe" ... ')</td>
                        <td>Change shell run command ffmpeg for start test stream</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>!file_exists($ffmpeg_folder . DIRECTORY_SEPARATOR . 'ffmpeg.exe') || !file_exists($ffmpeg_folder . DIRECTORY_SEPARATOR . 'ffprobe.exe')</td>
                        <td>Change file checker for ffmpeg and ffprobe</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Utility::getInstanceRunByPath()</td>
                        <td>Change process checker</td>
                        <td></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

_Note: There's some code that needs to change but is not documented here cause of future updates._

**Comment by sandyh90** [comment]
You can open again this issue if you still have question and problem after change code for linux config 😄

**Comment by sandyh90** [comment]
Feel free to open again this issue if you still have question and problem after changing code for linux config 😄
