### ISSUE TITLE
Linux or Docker Support 

### ISSUE THREAD

**Issue by amjiddader** [sandyh90/rockstream-streaming-relay-laravel#5]
Hello, 

I have installed on linux it was not working first but i fixed by following guide at #2  

Do you have plan to add support for Linux (out of the box).
Even docker would be easy if you have some coffee please do spend some time.
Create branch for linux ....

Thanks

**Comment by sandyh90** [comment]
Of course, I have plans to add support for Linux as soon as possible if I have free time to change some code to allow support between platforms, Thanks for the idea. I appreciate it. Feel free to open this issue if you have question again.😉
